apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app-dep
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-app-svc
  annotations:
    external-dns.alpha.kubernetes.io/hostname: psinc.click
    external-dns.alpha.kubernetes.io/ttl: "120"
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-app-ing
  labels:
    app: myapp
spec:
  ingressClassName: nginx
  rules:
  - host: psinc.click
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nginx-app-svc
            port:
              number: 80
